Frase = 'Eduardo de abreu'
print(Frase[0])
print(Frase[0:3])
print(Frase[0:17:2])
print(Frase[:7])
print(Frase[11:])
print(Frase[2::3])
print(Frase.count('u', 0, 16))
print(Frase.find('ar'))
print(Frase.find('andorid'))
print('de' in Frase)
print(Frase.replace('de', 'do'))
print(Frase.upper())
print(Frase.lower())
print(Frase.capitalize())
print(Frase.title())
print(Frase.strip())
print(Frase.rstrip())
print(Frase.lstrip())
print(Frase.split())
print('-'.join(Frase))
print(len(Frase.strip()))
